### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by ThomasUllrich666** [instana/instana-agent-operator#118]
You provide a dead link here:
https://github.com/instana/instana-agent-operator/blob/main/config/samples/instana_v1_instanaagent.yaml

`configuration_yaml: |
      # You can leave this empty, or use this to configure your instana agent.
      # See https://docs.instana.io/setup_and_manage/host_agent/on/kubernetes/`  <-- This link is dead

**Comment by hubx** [comment]
Fixed by #133
