### ISSUE TITLE
Question about operator framework

### ISSUE THREAD

**Issue by famartinrh** [instana/instana-agent-operator#16]
First of all, good job, the operator looks really good.
Is there any plan to extract all classes like `KubernetesResourceService` to another project that would potentially provide an operator framework for java ?
Probably no, but it would be really cool

**Comment by fstab** [comment]
Yes, we are thinking about that. One other component where this might be worthwhile is the resource cache, which we are currently refactoring in the `resource-cache` branch.

However, it's hard to estimate how much of the code will end up to be reusable and how much is application specific. I think it's good to focus on solving the concrete problem first, and then generalizing later.
