### ISSUE TITLE
The "controller-manager" Pods get OOMKilled in 2.1.0

### ISSUE THREAD

**Issue by bitgully** [instana/instana-agent-operator#170]
We have been running the Instana Agent Operator version 2.0.32 successfully.
After upgrading to 2.1.0, the controller-manager pods run out of memory.
In the older version, the memory usage was around 180Mi (below the Deployment's default limit of 200Mi).
In 2.1.0, the memory usage we observed was up to 350Mi and hence above the limit.

- Is there a memory-related bug in 2.1.0?
- Can the Deployment's limit be increased to 400Mi?
- Should an option for custom memory limits be provided?

**Comment by bitgully** [comment]
Fix has been released in version 2.1.1. Thanks!

**Comment by konrad-ohms** [comment]
Happy to help, thanks for reporting :slightly_smiling_face:
