### ISSUE TITLE
Automatic update of pods on Agent Configuration changes

### ISSUE THREAD

**Issue by asafarian** [instana/instana-agent-operator#51]
If we try to update the Instana Agent Configuration, we have to do this via the CustomRessourceDefinition.
But while we do so, we get the following errors:

    12:36:32 INFO  [co.in.op.CustomResourceState]] (cdi-handler) Custom resource agents.instana.io instana-agent/instana-agent has been modified. The operator currently does not support updates. The changes will be discarded. Please delete and re-create the custom resource if you want to change the configuration.

It helps add a feature that checks on Agent Configuration Changes and promotes those to the Agent.

Ad Hoc recommendations:
- Easy: Check via hash on the configuration if it has been changed and set an annotation on the DeamonSet so that the Agent will be updated automatically on the config's changes.

- Advanced: Make the config change available in the running pods, similar to the git Ops or config reload approach.

I am open to a discussion here.

Thanks
Ali

**Comment by mdonkers** [comment]
Hi Ali,

With the recent release of the 2.0.0 Operator based on Golang and Helm, this should have been properly addressed.
Making any configuration changes will apply them directly to the Agent.
Sorry for the long wait. Please let us know if everything works correctly for you now.
