### ISSUE TITLE
Provide support to reference Instana key in an existing Secret or Vault

### ISSUE THREAD

**Issue by hollisc** [instana/instana-agent-operator#59]
Currently the `InstanaAgent` custom resource provided by the operator expects the Instana Agent key to be explicitly set in `agent.key`.  

Request to update the CR to support the following which is already supported in the Agent Helm Chart: 
  - Option to specify an existing secret 
  - Option to support secret in Vault

**Comment by hollisc** [comment]
The helm chart supports the options:
  - agent.key
  - agent.downloadKey
  - agent.keysSecret

The InstanaAgent CR currently only supports the first 2 options.

**Comment by mdonkers** [comment]
Hi,

With the new release of the 2.0.0 Operator, we support the same options as the Helm chart.
Therefore I'm assuming that will cover your needs and therefore close this issue. Please re-open / create a new one if you find something still missing.
