### ISSUE TITLE
Instana 1.0.8 Operator does not show up in OpenShift console as an installed Operator

### ISSUE THREAD

**Issue by drewdouglass1** [instana/instana-agent-operator#68]
Just installed the latest operator on OCP 4.7 on the IBM cloud and as mentioned in the title it is not showing up as installed in any project. However, I can manually create an instance of the agent. 
![image](https://user-images.githubusercontent.com/26604925/134579958-c01c74bb-ac02-4dd8-80f6-d4259896a855.png)

**Comment by mdonkers** [comment]
Hi,

Could you please verify if this issue is still happening with the new 2.0.0 version of the Operator?

**Comment by drewdouglass1** [comment]
Just tried to deploy the 2.0 Operator and it is working as expected. One thing I did notice is that their are 3 Instana operators listed between the RedHat and IBM Catalogs. 
<img width="890" alt="image" src="https://user-images.githubusercontent.com/26604925/144624385-9dfe843d-dc36-44f9-9f69-0a29a14870c6.png">

**Comment by mdonkers** [comment]
Thanks!

We're uploading to at least three different repos. Perhaps they are joined somehow? Repos that we update and keep in sync:
- community operators (Operator Hub)
- RedHat certified operators
- RedHat Marketplace operators

Currently they are not in sync as we're having some initial publishing issues. But they should all be the same in a week or so.

I'll close this issue as the original problem is resolved.
