### ISSUE TITLE
When will the operator in OperatorHub be updated?

### ISSUE THREAD

**Issue by tormig-softronic** [instana/instana-agent-operator#73]
The available operator version in Openshift is 1.0.5 from may. But there is a 2.0.1 release available. When do you expect the operator in OperatorHub to be updated to the current version?

**Comment by mdonkers** [comment]
Hi,

Unfortunately we were having some difficulty in releasing the OLM Operator bundle in all places. It should now be available via;
- OperatorHub Community Operators: https://operatorhub.io/operator/instana-agent-operator/stable/instana-agent-operator.v2.0.1
- ArtifactHub (via OperatorHub): https://artifacthub.io/packages/olm/community-operators/instana-agent-operator
- RedHat certified Operators

The RedHat Marketplace Operators is still in progress but should follow soon.

Please let us know if there are even more places we currently overlooked.

**Comment by tormig-softronic** [comment]
Alright, 2.0.0 is actually there now in the Openshift OperatorHub. Do you know if there is a minium of kubernetes version?

**Comment by mdonkers** [comment]
I think we're supporting all the same versions as with the previous version.

Note that we will have a 2.0.2 version in a couple of days. You might want to wait for that, as it includes a fix for `SecurityContext` which might give problems on OpenShift.

**Comment by tormig-softronic** [comment]
2.0.2 fails on our Openshift 4.6 cluster but works in our 4.8. The log:
[controller-manager.log](https://github.com/instana/instana-agent-operator/files/7670780/controller-manager.log)
For some reason it lists "Provided APIs" twice, maybe some leftovers from a previous operator are still around? It also insist on "Manual approval required" despite choosing Automatic (which it does not on the 4.8 cluster).

**Comment by mdonkers** [comment]
Hi,
It looks like the Cert-Manager might be missing? This is needed when installing with the conversion WebHook: https://github.com/instana/instana-agent-operator#installing

Could you please retry?

With the provided API's do you perhaps mean the `v1beta1` and `v1` ? The `v1` is the new one but the conversion WebHook will automatically convert the `v1beta1` so the new Operator works with that as well.
If you don't need this conversion, you can also install without the WebHook (and thus also don't need the Cert-Manager).

**Comment by ac427** [comment]
missing `cert-manager.io/v1` seems to be the issue. Once I install `https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml` the operator gets installed without crashing the controller-manager.

I don't have to do it ins 4.8 openshift version. 

```
$oc apply -f https://github.com/instana/instana-agent-operator/releases/download/v2.0.3/instana-agent-operator.yaml
namespace/instana-agent unchanged
    

customresourcedefinition.apiextensions.k8s.io/agents.instana.io configured
serviceaccount/controller-manager unchanged
clusterrole.rbac.authorization.k8s.io/manager-role configured
clusterrole.rbac.authorization.k8s.io/leader-election-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/manager-rolebinding unchanged
configmap/manager-config unchanged
service/webhook-service created
deployment.apps/controller-manager configured
unable to recognize "https://github.com/instana/instana-agent-operator/releases/download/v2.0.3/instana-agent-operator.yaml": no matches for kind "Certificate" in version "cert-manager.io/v1"
unable to recognize "https://github.com/instana/instana-agent-operator/releases/download/v2.0.3/instana-agent-operator.yaml": no matches for kind "Issuer" in version "cert-manager.io/v1"
```

**Comment by mdonkers** [comment]
thanks. I guess that means we can close this issue?
(the Operator not working without the cert-manager is expected. Perhaps on OC 4.8 its already there or was installed for some other software?)
