### ISSUE TITLE
v2.0.5 fails on OCP

### ISSUE THREAD

**Issue by mossuchida** [instana/instana-agent-operator#81]
The new operator is failing - 2.0.4 works though

NAME                                  READY   STATUS             RESTARTS   AGE
controller-manager-5c7d55d897-jd4z6   0/1     ImagePullBackOff   0          4m1s
controller-manager-5c7d55d897-pml2v   0/1     ImagePullBackOff   0          4m1s

**Comment by donovanmuller** [comment]
The controller image for `2.0.5` has not been published to Docker Hub https://github.com/instana/instana-agent-operator/releases/tag/v2.0.5

**Comment by donovanmuller** [comment]
@mossuchida this should be solved now that `2.0.5` has been [re-released](https://github.com/instana/instana-agent-operator/releases/tag/v2.0.5)
